### ISSUE TITLE
Invalid Ping

### ISSUE THREAD

**Issue by ghost** [xDefcon/bungee-ping#1]
Hello,

I have a problem with BungeePing : sometimes when I do /ping, the ping is over 2000ms.

I have a really good connection, I have no lag and on the minecraft server list my ping is like 12ms.

Can you fix this please ?

Sorry for my english, I am french

Thanks a lot

**Comment by xDefcon** [comment]
Does this happen immediately after you join the server? Have you tried to wait 10/15 seconds, and then do the /ping command?

The ping of a player is obtained by using the BungeeCord's built-in method. I have never had problems with it, but I'm glad to solve your issue if you provide further information.

**Comment by ghost** [comment]
Hi, after a restart of BungeeCord when I do /ping I have normal ping.

But I found a big problem : all players when they do /ping have the same ping !

When I go on TeamSpeak, I have 12ms and my friend who have a bad connection have 35ms but on the server we both have 14ms (and all players have the same).

Thanks a lot

**Comment by xDefcon** [comment]
This is possible, but the ping is calculated by BungeeCord, so it could happen that a player has the same ping of another one, but if you try to connect via proxy, or with a slower internet connection, your ping will be different. 

The ping is unique and is calculated for each player. And TeamSpeak 3 is different from Minecraft, the ping should be similar, but not the same.

**Comment by ghost** [comment]
But all  the players has exactly the same ping but not the minecraft serverlist, they have differents ping. How is possible I do test on 5 personnes with every people got 15ms, me with optical fiber won t got the same ping of a player with adsl.

I think I will use Spigot ping.

If you can fix it, thanks.

**Comment by xDefcon** [comment]
Have you tried to check the ping (by typing **/ping**) after some seconds?

**Comment by ghost** [comment]
Sorry for my late reply, but I m sure the ping don t work : 

I do a test with me and a friend : 

My friend who have more than 200ms and in game he is teleporting when he do /ping always have 22ms and me have the same ping but with no lag

When we do /ping with 30min of decalage, we both have the same result

Thanks

**Comment by xDefcon** [comment]
I will try to reproduce your problem and find a solution if the problem really exists.

**Comment by Brokkonaut** [comment]
Have a look at https://github.com/xDefcon/bungee-ping/blob/master/src/com/xdefcon/bungeeping/PingCommand.java#L21-L22 
You are replacing the this.plugin.message with a message that does no longer contain %ping%. You have to use a local variable instead..

**Comment by xDefcon** [comment]
Thanks for the help @Brokkonaut I really have a poor amount of time in this period to dedicate to my projects. 

I will fix this bug as soon as possible.
